[project]
name = "advent2024"
version = "0.1.0"
description = "Advent of Code 2024"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "ipython>=8.30.0",
    "pdbpp>=0.10.3",
    "ruff>=0.8.1",
]
